#!/usr/bin/env bash
# Installs Nginx with the following configurations:

#comprove all dependences to server
# execute one update first
function dependences(){
	apt-get update
	apt-get install -y nginx
	service nginx start
	config_response
}

# The function execute one configuration to nginx server to http response
# to curl comman the result is Hello World!
function config_response(){
	echo "Hello World" > /var/www/html/index.html
	service nginx restart
}

#Function main is the init to all functions
function main(){
	dependences;
}

# Declare the flush to progam
main;
