#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80 to HTTP protocol.
#+    Returns a page containing "Hello World!" when queried
#++    at the root with a curl GET request.

#comprove all dependences to server
# execute one update first
function dependences(){
	which nginx &>1
	if [ "$(echo $?)" -eq 1 ]; then
		apt-get update
		apt-get install -y nginx
		config_response

	else
		service nginx start
		config_response
	fi
}

# The function execute one configuration to nginx server to http response
# to curl comman the result is Hello World!
function config_response(){
	echo "Hello World!" > /var/www/html/index.html
	service nginx restart
}

#Function main is the init to all functions
function main(){
	dependences;
}

# Declare the flush to progam
main;
