#!/usr/bin/env bash
apt-get update
apt-get install -y nginx


sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
newlines="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo touch /var/www/html/index.html
sudo echo "Hello World" > /var/www/html/index.html
sudo sed -i "26i $newlines" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
