#!/usr/bin/env bash
#Configure one load balancer to Haproxy

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen webapp 0.0.0.0:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 3428-web-01 35.196.128.244:80 check\n\tserver 3428-web-02 34.235.116.181:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
