#!/usr/bin/env bash
# display Process Identifier with awk statement
# Kill Process to infinite beyond.
# Print i am invincible with SIGTERM trap
#   Deletes the file /var/run/holbertonscript.pid and terminates upon
#+  receiving a SIGQUIT or SIGTERM.

terminator() {
  rm /var/run/holbertonscript.pid
  exit
}

echo "$$" > /var/run/holbertonscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done