#!/usr/bin/env bash
# define new function display 10 times with until statement
echo $$ > /var/run/myscript.pid
trap "echo 'I hate the kill command'; exit" SIGTERM
trap "rm -f /var/run/my.pid; exit" SIGTERM SIGQUIT
trap "echo 'Y U no love me?!'; exit" SIGINT
while true
do
	echo "To infinity and beyond"
	sleep 2
done