#!/usr/bin/env bash
# display Process Identifier with awk statement
# Kill Process to infinite beyond.
# Print i am invincible with SIGTERM trap

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done