#!/usr/bin/env bash
# define new function display 10 times with until statement
for count in {1..100}
do
  if (( count % 3 == 0 && count % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( count % 3 == 0 ))
  then
    echo "Fizz"
  elif (( count % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo $count
    ((count++))
  fi
done