#!/usr/bin/env bash
# define new function display 10 times with until statement
declare -i count=0
while [ $count -lt 10 ]
do
  if [ $count -eq 3 ]
  then
    echo "bad luck"
  elif [ $count -eq 7 ]
  then
    echo "good luck"
  else
    echo "Holberton School"
  fi
  (( count++ ))
done