#!/usr/bin/env bash
# define new function display 10 times with until statement
count=1
while [ $count -le 10 ]
do
  if [ $count == 4 ]
  then
    echo "bad luck"
  elif [ $count == 8 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( count++ ))
done