#!/usr/bin/env bash
# define new function display 10 times with until statement
count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 4 ]
  then
    echo "bad luck"
  elif [ $count -eq 8 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( count++ ))
done