#!/usr/bin/env bash
# define new function display 10 times with until statement
count=1
while [ $count -le 20 ]
do
  case $count in
    "4")
    echo "bad luck from China"
    ;;
    "9")
    echo "bad luck from Japan"
    ;;
    "17")
    echo "bad luck from Italy"
    ;;
  esac
  echo $count
  (( count++ ))
done