#!/usr/bin/env bash
# define new function display 10 times with until statement
count=1
while [ $count -le 20 ]
do
  if [ $count == 4 ]
  then
    echo "bad luck from China"
  elif [ $count == 9 ]
  then
    echo "bad luck from Japan"
  elif [ $count == 17 ]
  then
    echo "bad luck from Italy"
  else
    echo $count
  fi
  (( count++ ))
done