#!/bin/bash
#Configure ufw so that it blocks all incoming traffic, except the following TCP ports:
#
#    22 (SSH)
#    443 (HTTPS SSL)
#    80 (HTTP)
apt-get install ufw -y
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw enable
