#!/bin/bash
#Configure ufw so that it blocks all incoming traffic, except the following TCP ports:
#
#    22 (SSH)
#    443 (HTTPS SSL)
#    80 (HTTP)
apt-get install ufw -y

command=("allow http" "allow https" "allow ssh")

for rules in "${command[@]}";
do
	ufw $rules
done
ufw enable
