#!/usr/bin/env bash
# Bash script that configures an Ubuntu server.
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.
FILE="/etc/hosts"
cp $FILE ~/hosts.new
sed -i 's/127.*$/127.0.0.2  localhost\n8.8.8.8 facebook.com/' ~/hosts.new
echo "127.0.0.2 localhost"
cp -f ~/hosts.new $FILE
