#!/usr/bin/env bash

declare -a files=(
	'0-use_a_private_key'
	'1-create_ssh_key_pair'
	'2-ssh_config'
	'100-puppet_ssh_config.pp'
	)

function file_exist(){
	for file in "${files[@]}"
	do
		cat "$file" 2&>/dev/null
		if [ $(echo $?) -eq 1 ]; then
			echo -ne "\n\n[!] Errors Files missing \n\t${files[$file]}\n"
			return 1
		fi
	done
	echo -ne "\n[*] Congrats!\n\tAll files exist\n"
	return 0
}

function main(){
	file_exist;
	if [ $(echo $?) -eq 1 ]; then
		echo -ne "\nError en el programa"
		exit 1
	else
		echo -ne "\nEl programa termino correctamente"
		exit 0
	fi
}

main;
